Repository Pepsi-Club/WhereMyBus-iOS, pull requests merged in 2024-04, with the labels that each got.

#181 [Fix] 긴 이름의 버스정류장 width 수정
  Projects/Feature/BusStopFeature/Sources/View/BusStopInfoHeaderView.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
Labels: 버그

#189 [Fix] #188 NearMap ViewWillAppear 이벤트 핸들링 수정
  Makefile
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
Labels: 버그

#200 Feat/#187
  .swiftlint.yml
  Projects/DesignSystem/Resources/Assets.xcassets/mapBusStopGray.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/mapBusStopGray.imageset/mapBusStopGray.png
  Projects/Feature/NearMapFeature/Sources/NMapsClustreing/BusStopClusteringKey.swift
  Projects/Feature/NearMapFeature/Sources/NMapsClustreing/LeafMarkerUpdater.swift
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
Labels: 기능추가

#204 Fix/#201
  Document/ko/iPhone_15_Pro-5_NearMap.png
  Document/ko/iPhone_8_Plus-5_NearMap.png
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Environment.swift
  Projects/App/Tests/BCUITests.swift
  Projects/Feature/AlarmFeature/Sources/ViewController/AddRegularAlarmViewController.swift
  Projects/Feature/AlarmFeature/Sources/ViewController/RegularAlarmViewController.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  Projects/Feature/SearchFeature/Sources/View/BusStopInfoView.swift
  Projects/Feature/SearchFeature/Sources/ViewController/SearchViewController.swift
  Projects/Feature/SettingsFeature/Sources/ViewController/SettingsViewController.swift
Labels: 버그

#206 Feat/#205
  Makefile
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/InfoPlist.swift
  Projects/App/NotificationExtension/NotificationService.swift
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/Coordinator/AppCoordinator.swift
  Projects/App/Sources/DeeplinkHandler.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Widget/MockData.swift
  Projects/App/Widget/Provider.swift
  Projects/App/Widget/WMBEntry.swift
  Projects/App/Widget/WMBWidget.swift
  Projects/App/Widget/WMBWidgetView.swift
  Projects/App/Widget/WidgetUseCase.swift
  Projects/Data/Sources/Service/LocationService/DefaultLocationService.swift
  Projects/Domain/Sources/Entity/Response/LocationStatus.swift
  Projects/Domain/Sources/UseCase/DefaultNearMapUseCase.swift
  Projects/Domain/Sources/UseCase/DefaultSearchUseCase.swift
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
Labels: 버그, 기능추가

#219 Fix/#190
  Projects/Feature/BusStopFeature/Sources/View/BusTableViewCell.swift
Labels: 버그

#212 Fix/#198
  Makefile
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/XCConfig.swift
  Projects/App/Resources/Model.xcdatamodeld/Model.xcdatamodel/contents
  Projects/App/Sources/AppDelegate+Register.swift
  Projects/Core/Sources/Extension/String+.swift
  Projects/Core/Sources/PushNotificationRequestable.swift
  Projects/CoreDataService/Sources/DefaultCoreDataService.swift
  Projects/Data/Sources/DTO/AddRegularAlarmDTO.swift
  Projects/Data/Sources/DTO/CoreDataModelObject/RegularAlarmResponseMO+CoreDataClass.swift
  Projects/Data/Sources/DTO/CoreDataModelObject/RegularAlarmResponseMO+CoreDataProperties.swift
  Projects/Data/Sources/DTO/RemoveRegularAlarmDTO.swift
  Projects/Data/Sources/Repository/DefaultRegularAlarmRepository.swift
  Projects/Data/Sources/Service/DefaultRegularAlarmEditingService.swift
  Projects/Data/Sources/Service/NotificationService/DefaultLocalNotificationService.swift
  Projects/Data/Sources/Service/NotificationService/DefaultPushNotificationService.swift
  Projects/Domain/Sources/Entity/Request/AddRegularAlarmRequest.swift
  Projects/Domain/Sources/Entity/Request/RemoveRegularAlarmRequest.swift
  Projects/Domain/Sources/Entity/Response/RegularAlarmResponse.swift
  Projects/Domain/Sources/RepositoryInterface/RegularAlarmRepository.swift
  Projects/Domain/Sources/Service/NotificationService/PushNotificationService.swift
  Projects/Domain/Sources/UseCase/DefaultAddRegularAlarmUseCase.swift
  Projects/Domain/Sources/UseCase/DefaultRegularAlarmUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/RegularAlarmUseCase.swift
  Projects/Feature/AlarmFeature/Sources/ViewController/AddRegularAlarmViewController.swift
  Projects/Feature/AlarmFeature/Sources/ViewModel/AddRegularAlarmViewModel.swift
  Projects/Feature/AlarmFeature/Sources/ViewModel/RegularAlarmViewModel.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewModel/FavoritesViewModel.swift
  Projects/Feature/SettingsFeature/Sources/ViewController/SettingsViewController.swift
  Projects/FeatureDependency/Sources/Mock/MockFavoritesRepository.swift
  Projects/FeatureDependency/Sources/Mock/MockLocalNotificationService.swift
  Projects/FeatureDependency/Sources/Mock/MockRegualrAlarmEditingService.swift
  Projects/NetworkService/Sources/EndPoint/EndPoint.swift
  Projects/NetworkService/Sources/EndPoint/PushNotificationEndPoint.swift
  Projects/NetworkService/Sources/EndPoint/RegularAlarmEndPoint/AddRegularAlarmEndPoint.swift
  Projects/NetworkService/Sources/EndPoint/RegularAlarmEndPoint/RegularAlarmEndPoint.swift
  Projects/NetworkService/Sources/EndPoint/RegularAlarmEndPoint/RemoveRegularAlarmEndPoint.swift
  Projects/NetworkService/Sources/NetworkService/DefaultNetworkService.swift
Labels: 기능추가

#229 Fix/#228
  Projects/Core/Sources/Extension/Sequence+.swift
  Projects/Core/Sources/Extension/String+.swift
  Projects/Data/Sources/DTO/FetchRegularAlarmDTO.swift
  Projects/Data/Sources/DTO/RegularAlarmSyncValidation.swift
  Projects/Data/Sources/Repository/DefaultRegularAlarmRepository.swift
  Projects/NetworkService/Sources/EndPoint/RegularAlarmEndPoint/FetchRegularAlarmEndPoint.swift
Labels: 기능추가

#226 Fix/#225
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/XCConfig.swift
  Projects/CoreDataService/Sources/DefaultCoreDataService.swift
  Projects/Domain/Sources/Service/LocationService/LocationService.swift
  Projects/Domain/Sources/UseCase/DefaultRegularAlarmUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/RegularAlarmUseCase.swift
Labels: 기능추가

#237 [UI] Background Color change
  Projects/Feature/SearchFeature/Sources/View/SearchNearStopInformationView.swift
Labels: UI/UX

#241 [UI] AppLogo 화질 개선
  Projects/App/Resources/AppLogo.png
  Projects/App/Resources/Base.lproj/LaunchScreen.storyboard
  Projects/App/Widget/ArrivalInfo/View/View/ArrivalInfoPracView.swift
Labels: UI/UX, 기능개선

#240 [Feat] 처음 선택된 ClusterMaker값 처리
  Projects/Feature/NearMapFeature/Sources/NMapsClustreing/LeafMarkerUpdater.swift
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
Labels: 기능개선

#248 [Setting] 위젯 타겟 제거, 번들버전 한글시간 기준으로 수정
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Environment.swift
  Projects/App/Project.swift
Labels: 🌏 앱 배포

#244 [Feat] 2x2 4x2 Widget Base작업
  Projects/App/Project.swift
  Projects/App/Widget/ArrivalInfo/Intent/ArrivalInfoIntent.swift
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoMediumView.swift
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoSmallView.swift
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoView.swift
  Projects/App/Widget/ArrivalInfo/View/RefreshView.swift
  Projects/App/Widget/Extension/ArrivalState+.swift
  Projects/App/Widget/Extension/Font+.swift
  Projects/App/Widget/Extension/View+.swift
  Projects/DesignSystem/Resources/Assets.xcassets/LogoColor.colorset/Contents.json
Labels: ✨ 기능추가, 💻 UI/UX

#261 [Feat] 알람 -> 정류장: 쓰로틀 작업
  Projects/Feature/BusStopFeature/Sources/Coordinator/DafaultBusStopCoordinator.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/BusStopFeature/Sources/ViewModel/BusStopViewModel.swift
Labels: 📬 기능개선

#264 [Fix] 검색화면 주변정류장 업데이트 주기 수정
  Projects/Domain/Sources/UseCase/DefaultSearchUseCase.swift
  Projects/Feature/SearchFeature/Sources/ViewModel/SearchViewModel.swift
Labels: 📬 기능개선
