Repository Pepsi-Club/WhereMyBus-iOS, pull requests merged in 2024-05, with the labels that each got.

#269 Feat/#263 UI변경작업
  Projects/App/Project.swift
  Projects/App/Resources/AppLogo.png
  Projects/App/Resources/Base.lproj/LaunchScreen.storyboard
  Projects/App/Resources/Lottie/cleanMap.json
  Projects/App/Resources/Lottie/goingBus.json
  Projects/App/Resources/Lottie/list.json
  Projects/App/Resources/Lottie/searchLocation.json
  Projects/App/Resources/Lottie/star.json
  Projects/App/Resources/applogo.png
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoSmallView.swift
  Projects/DesignSystem/Project.swift
  Projects/DesignSystem/Resources/Assets.xcassets/EmptyFavoriteImage.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/EmptyFavoriteImage.imageset/EmptyFavoriteImage.png
  Projects/DesignSystem/Resources/Assets.xcassets/OvernightBusColor.colorset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/TableViewColor.colorset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/busStop2.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/busStop2.imageset/busStop2.png
  Projects/DesignSystem/Resources/Assets.xcassets/busStop3.imageset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/busStop3.imageset/busStop3.png
  Projects/DesignSystem/Sources/LottieAnimationView+.swift
  Projects/DesignSystem/Sources/LottieView +.swift
  Projects/DesignSystem/Sources/SearchBusStopBtn.swift
  Projects/Feature/AlarmFeature/Sources/View/RegularAlarmTVCell.swift
  Projects/Feature/BusStopFeature/Sources/View/BusStopInfoHeaderView.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/HomeFeature/Sources/View/EmptyFavoritesView.swift
  Projects/Feature/HomeFeature/Sources/View/FavoritesHeaderView.swift
  Projects/Feature/HomeFeature/Sources/View/FavoritesTVCell.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  Projects/Feature/NearMapFeature/Sources/View/BusStopInformationView.swift
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
  Projects/Feature/SearchFeature/Sources/View/SearchNearStopInformationView.swift
  Projects/Feature/SearchFeature/Sources/View/SearchTextFieldView.swift
  Projects/Feature/SearchFeature/Sources/ViewController/SearchViewController.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/ResourceSynthesizers/Lottie.stencil
  Tuist/Templates/framework/Lottie.stencil
Labels: 💻 UI/UX

#280 UI/#237 네비게이션 위치 통일
  Projects/Feature/BusStopFeature/Sources/View/BusStopInfoHeaderView.swift
Labels: 💻 UI/UX

#284 Bug/#283 NearMapView 위치정보권한 없을 때 나오는 infomationView 수정
  Projects/Domain/Sources/UseCase/DefaultNearMapUseCase.swift
  Projects/Feature/NearMapFeature/Sources/View/BusStopInformationView.swift
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
  Projects/Feature/SearchFeature/Sources/ViewModel/SearchViewModel.swift
Labels: 🐞버그픽스

#288 Fix/#287 NearMapView에 InformainView 세브론UI 설정
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
  Projects/Feature/NearMapFeature/Sources/ViewModel/NearMapViewModel.swift
Labels: 💻 UI/UX, 📬 기능개선

#289 Fix/#285 설정 Icon 떴다 안떴다 하는 버그 및 UI수정
  Projects/DesignSystem/Resources/Assets.xcassets/Color.colorset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/Gray3.colorset/Contents.json
  Projects/DesignSystem/Resources/Assets.xcassets/Gray5Minor.colorset/Contents.json
  Projects/DesignSystem/Sources/Appearance.swift
  Projects/Feature/HomeFeature/Sources/View/EmptyFavoritesView.swift
  Projects/Feature/HomeFeature/Sources/View/FavoritesHeaderView.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  Projects/Feature/SearchFeature/Sources/View/SearchNearStopInformationView.swift
  Projects/Feature/SearchFeature/Sources/ViewController/SearchViewController.swift
  Projects/Feature/SettingsFeature/Sources/View/SettingButton.swift
  Projects/Feature/SettingsFeature/Sources/ViewController/AlarmSettingViewController.swift
  Projects/Feature/SettingsFeature/Sources/ViewController/PrivacyWebViewController.swift
Labels: 🐞버그픽스, 💻 UI/UX

#293 Fix/#292 distance에 '알수없음'이 들어오는 로직 수정
  Projects/Domain/Sources/UseCase/DefaultNearMapUseCase.swift
  Projects/Feature/NearMapFeature/Sources/ViewController/NearMapViewController.swift
Labels: 🐞버그픽스, 💻 UI/UX

#295 UI/#291 Cell에 text 흘러넘치는 UI오류
  Projects/Feature/NearMapFeature/Sources/View/BusStopInformationView.swift
  Projects/Feature/SearchFeature/Sources/View/BusStopInfoView.swift
Labels: 💻 UI/UX

#298 UI/#297 즐겨찾기 위치 수정
  Projects/Feature/BusStopFeature/Sources/View/BusTableViewCell.swift
Labels: 💻 UI/UX

#301 ReleaseFix/#300 릴리즈 Fix
  .github/workflows/upload_testflight.yml
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Environment.swift
  Projects/App/Project.swift
  Projects/Core/Sources/Extension/UIScrollView+.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  fastlane/Fastfile
Labels: 🍕릴리즈픽스

#268 feat/#267 BusStopFeature Refresh Throttle 처리
  Projects/Domain/Sources/UseCase/DefaultBusStopUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/BusStopUseCase.swift
  Projects/Feature/BusStopFeature/Sources/ViewModel/BusStopViewModel.swift
Labels: ✨ 기능추가, 📬 기능개선

#304 Setting/#303 구글 애널리틱스 환경 세팅
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Scheme.swift
  Projects/App/Project.swift
  Projects/App/Sources/AppDelegate+Firebase.swift
  Projects/App/Sources/AppDelegate.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  Tuist/Templates/framework/project.stencil
Labels: ⚙ 환경세팅

#307 Feat/#302 FirebaseAnalytics 작업
  Makefile
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Environment.swift
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Scheme.swift
  Projects/App/Project.swift
  Projects/App/Resources/Base.lproj/LaunchScreen.storyboard
  Projects/App/Sources/AppDelegate+Firebase.swift
  Projects/App/Sources/AppDelegate.swift
  Projects/Core/Sources/Extension/UIColor+.swift
  Projects/Data/Project.swift
  Projects/Data/Sources/Repository/DefaultBusStopArrivalInfoRepository.swift
  Projects/DesignSystem/Resources/Assets.xcassets/cellColor.colorset/Contents.json
  Projects/Feature/HomeFeature/Sources/View/EmptyFavoritesView.swift
  Projects/Feature/NearMapFeature/Sources/View/BusStopInformationView.swift
  Projects/Feature/SearchFeature/Sources/View/SearchTextFieldView.swift
  Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨ 기능추가, ⚙ 환경세팅

#265 Feat/#255 즐겨찾기 Fetch 페이지네이션 처리
  Projects/App/Widget/ArrivalInfo/ArrivalInfoUseCase.swift
  Projects/App/Widget/ArrivalInfo/Intent/Parameter/FavoritesOptionProvider.swift
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoSmallView.swift
  Projects/App/Widget/Extension/ArrivalState+.swift
  Projects/Core/Sources/BCTimer.swift
  Projects/CoreDataService/Sources/CoreDataDirectory.swift
  Projects/CoreDataService/Sources/DefaultCoreDataService.swift
  Projects/Data/Sources/Repository/DefaultFavoritesRepository.swift
  Projects/Domain/Sources/Entity/Response/BusStopArrivalInfoResponse.swift
  Projects/Domain/Sources/Entity/Response/FavoritesBusResponse.swift
  Projects/Domain/Sources/RepositoryInterface/FavoritesRepository.swift
  Projects/Domain/Sources/UseCase/DefaultFavoritesUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/FavoritesUseCase.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewModel/FavoritesViewModel.swift
  Projects/FeatureDependency/Sources/Mock/MockFavoritesRepository.swift
Labels: ✨ 기능추가, 📬 기능개선

#312 Feat/#245 홈 / 알람 쓰로틀, 무한스크롤 적용
  Projects/App/Widget/ArrivalInfo/ArrivalInfoUseCase.swift
  Projects/App/Widget/ArrivalInfo/Intent/Parameter/FavoritesOptionProvider.swift
  Projects/App/Widget/ArrivalInfo/View/ArrivalInfoSmallView.swift
  Projects/App/Widget/Extension/ArrivalState+.swift
  Projects/Core/Sources/BCTimer.swift
  Projects/CoreDataService/Sources/CoreDataDirectory.swift
  Projects/CoreDataService/Sources/DefaultCoreDataService.swift
  Projects/Data/Sources/Repository/DefaultFavoritesRepository.swift
  Projects/Domain/Sources/Entity/Response/BusStopArrivalInfoResponse.swift
  Projects/Domain/Sources/Entity/Response/FavoritesBusResponse.swift
  Projects/Domain/Sources/RepositoryInterface/FavoritesRepository.swift
  Projects/Domain/Sources/UseCase/DefaultBusStopUseCase.swift
  Projects/Domain/Sources/UseCase/DefaultFavoritesUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/BusStopUseCase.swift
  Projects/Domain/Sources/UseCase/Protocol/FavoritesUseCase.swift
  Projects/Feature/BusStopFeature/Sources/Coordinator/DafaultBusStopCoordinator.swift
  Projects/Feature/BusStopFeature/Sources/ViewController/BusStopViewController.swift
  Projects/Feature/BusStopFeature/Sources/ViewModel/BusStopViewModel.swift
  Projects/Feature/HomeFeature/Sources/ViewController/FavoritesViewController.swift
  Projects/Feature/HomeFeature/Sources/ViewModel/FavoritesViewModel.swift
  Projects/FeatureDependency/Sources/Mock/MockFavoritesRepository.swift
Labels: ✨ 기능추가

#316 Release fix/#315 v1.2.4 배포에 필요한 사항 수정
  .github/workflows/upload_testflight.yml
  Plugins/EnvironmentPlugin/ProjectDescriptionHelpers/Environment.swift
  Projects/App/Resources/total_stationList.json
  Projects/Data/Sources/Repository/DefaultStationListRepository.swift
Labels: 🍕릴리즈픽스
